services:
  - type: web
    name: jobgraph-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: COGNODB_URI
        sync: false
      - key: COGNODB_USERNAME
        value: cognodb
      - key: COGNODB_PASSWORD
        sync: false
